import 'package:flutter/material.dart';

/// All application colors derived from the Stitch design system.
///
/// Light theme uses the direct Stitch palette.
/// Dark theme uses inverted/adapted values per the design system guidance:
/// _"In Dark Mode, surfaces transition to a deep charcoal-slate (#0D1111)
/// rather than pure black to preserve the softness of glassmorphic shadows."_
abstract final class AppColors {
  // ── Light Color Scheme ─────────────────────────────────────────────
  static const ColorScheme lightScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF0F5238),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF2D6A4F),
    onPrimaryContainer: Color(0xFFA8E7C5),
    primaryFixed: Color(0xFFB1F0CE),
    primaryFixedDim: Color(0xFF95D4B3),
    onPrimaryFixed: Color(0xFF002114),
    onPrimaryFixedVariant: Color(0xFF0E5138),
    secondary: Color(0xFF9B4500),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFC8A40),
    onSecondaryContainer: Color(0xFF672C00),
    secondaryFixed: Color(0xFFFFDBC9),
    secondaryFixedDim: Color(0xFFFFB68D),
    onSecondaryFixed: Color(0xFF331200),
    onSecondaryFixedVariant: Color(0xFF763300),
    tertiary: Color(0xFF0D5237),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFF2C6A4E),
    onTertiaryContainer: Color(0xFFA7E7C4),
    tertiaryFixed: Color(0xFFB0F1CC),
    tertiaryFixedDim: Color(0xFF94D4B1),
    onTertiaryFixed: Color(0xFF002113),
    onTertiaryFixedVariant: Color(0xFF0C5136),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF93000A),
    surface: Color(0xFFFCF9F8),
    onSurface: Color(0xFF1B1B1B),
    surfaceDim: Color(0xFFDCD9D9),
    surfaceBright: Color(0xFFFCF9F8),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF6F3F2),
    surfaceContainer: Color(0xFFF0EDED),
    surfaceContainerHigh: Color(0xFFEAE7E7),
    surfaceContainerHighest: Color(0xFFE5E2E1),
    onSurfaceVariant: Color(0xFF404943),
    outline: Color(0xFF707973),
    outlineVariant: Color(0xFFBFC9C1),
    inverseSurface: Color(0xFF313030),
    onInverseSurface: Color(0xFFF3F0EF),
    inversePrimary: Color(0xFF95D4B3),
    surfaceTint: Color(0xFF2C694E),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
  );

  // ── Dark Color Scheme ──────────────────────────────────────────────
  static const ColorScheme darkScheme = ColorScheme(
    brightness: Brightness.dark,
    // Deep charcoal-slate per Stitch guidance
    primary: Color(0xFF95D4B3),
    onPrimary: Color(0xFF002114),
    primaryContainer: Color(0xFF0E5138),
    onPrimaryContainer: Color(0xFFB1F0CE),
    primaryFixed: Color(0xFFB1F0CE),
    primaryFixedDim: Color(0xFF95D4B3),
    onPrimaryFixed: Color(0xFF002114),
    onPrimaryFixedVariant: Color(0xFF0E5138),
    secondary: Color(0xFFFFB68D),
    onSecondary: Color(0xFF331200),
    secondaryContainer: Color(0xFF763300),
    onSecondaryContainer: Color(0xFFFFDBC9),
    secondaryFixed: Color(0xFFFFDBC9),
    secondaryFixedDim: Color(0xFFFFB68D),
    onSecondaryFixed: Color(0xFF331200),
    onSecondaryFixedVariant: Color(0xFF763300),
    tertiary: Color(0xFF94D4B1),
    onTertiary: Color(0xFF002113),
    tertiaryContainer: Color(0xFF0C5136),
    onTertiaryContainer: Color(0xFFB0F1CC),
    tertiaryFixed: Color(0xFFB0F1CC),
    tertiaryFixedDim: Color(0xFF94D4B1),
    onTertiaryFixed: Color(0xFF002113),
    onTertiaryFixedVariant: Color(0xFF0C5136),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF0D1111),
    onSurface: Color(0xFFF3F0EF),
    surfaceDim: Color(0xFF0D1111),
    surfaceBright: Color(0xFF353434),
    surfaceContainerLowest: Color(0xFF080C0C),
    surfaceContainerLow: Color(0xFF1B1B1B),
    surfaceContainer: Color(0xFF1F1F1F),
    surfaceContainerHigh: Color(0xFF2A2A2A),
    surfaceContainerHighest: Color(0xFF353434),
    onSurfaceVariant: Color(0xFFBFC9C1),
    outline: Color(0xFF89938C),
    outlineVariant: Color(0xFF404943),
    inverseSurface: Color(0xFFF3F0EF),
    onInverseSurface: Color(0xFF313030),
    inversePrimary: Color(0xFF0F5238),
    surfaceTint: Color(0xFF95D4B3),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
  );
}
